@base_url = http://localhost:5120

@general_fake_id_for_all_situations = 775d3df4-cb3b-4ec1-b1d1-c6a56c0bef56

@unidade_organizacional_fake_id = {{UnidadeOrganizacionalFakeId.response.body.$.unidadeOrganizacionalId}}
@unidade_organizacional_oficial_id = {{UnidadeOrganizacionalOficialId.response.body.$.unidadeOrganizacionalId}}

@espaco_fake_id = {{EspacoFakeId.response.body.$.espacoId}}

@token = {{Login.response.body.$.token}}


### UnidadeOrganizacional_Cadastrar_201_Oficial
POST {{base_url}}/v1/unidades-organizacionais
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "matrizId": null,
  "cnpj": "60935686000134",
  "razaoSocial": "Zênite Tecnologia Ltda.",
  "nomeFantasia": "Zênite Tech",
  "cep": "35604000",
  "endereco": "Rua Tamoios",
  "numero": "329",
  "bairro": "Centro",
  "cidade": "Moema",
  "uf": "MG",
  "pais": "Brasil",
  "email": "zenitetecnologias@gmail.com.br",
  "telefone": "37999654512"
}
###

### UnidadeOrganizacional_Cadastrar_201_Fake
POST {{base_url}}/v1/unidades-organizacionais
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "matrizId": null,
  "cnpj": "60163639000110",
  "razaoSocial": "Ricardo e Isis Marketing ME (Fake)",
  "nomeFantasia": null,
  "cep": null,
  "endereco": null,
  "numero": null,
  "bairro": null,
  "cidade": null,
  "uf": null,
  "pais": null,
  "email": null,
  "telefone": null
}
###

### UnidadeOrganizacional_Cadastrar_400_CamposVazios
POST {{base_url}}/v1/unidades-organizacionais
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "matrizId": null,
  "cnpj": null,
  "razaoSocial": null,
  "nomeFantasia": null,
  "cep": null,
  "endereco": null,
  "numero": null,
  "bairro": null,
  "cidade": null,
  "uf": null,
  "pais": null,
  "email": null,
  "telefone": null
}
###

### UnidadeOrganizacional_Cadastrar_400_CnpjInvalido
POST {{base_url}}/v1/unidades-organizacionais
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "matrizId": null,
  "cnpj": "1610404700013B",
  "razaoSocial": "Ricardo e Isis Marketing ME (Fake)",
  "nomeFantasia": null,
  "cep": null,
  "endereco": null,
  "numero": null,
  "bairro": null,
  "cidade": null,
  "uf": null,
  "pais": null,
  "email": null,
  "telefone": null
}
###

### UnidadeOrganizacional_Cadastrar_400_RegistroDuplicado
POST {{base_url}}/v1/unidades-organizacionais
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "matrizId": null,
  "cnpj": "60935686000134",
  "razaoSocial": "Ricardo e Isis Marketing ME (Fake)",
  "nomeFantasia": null,
  "cep": null,
  "endereco": null,
  "numero": null,
  "bairro": null,
  "cidade": null,
  "uf": null,
  "pais": null,
  "email": null,
  "telefone": null
}
###

### UnidadeOrganizacional_Cadastrar_500
POST {{base_url}}/v1/unidades-organizacionais
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "matrizId": null,
  "cnpj": "45907344000117",
  "razaoSocial": "Ricardo e Isis Marketing ME (Fake)",
  "nomeFantasia": null,
  "cep": null,
  "endereco": null,
  "numero": null,
  "bairro": null,
  "cidade": null,
  "uf": "Minas Gerais",
  "pais": null,
  "email": null,
  "telefone": null
}
###


### UnidadeOrganizacional_Obter_200
GET {{base_url}}/v1/unidades-organizacionais
###

### UnidadeOrganizacional_Obter_200_ComPaginacao
GET {{base_url}}/v1/unidades-organizacionais?skip=1&top=1
###

### UnidadeOrganizacional_Obter_200_ComFiltro
# @name UnidadeOrganizacionalFakeId
GET {{base_url}}/v1/unidades-organizacionais?skip=0&top=10&cnpj=0001&razaoSocial=fake
###

### UnidadeOrganizacional_Obter_200_Vazio
GET {{base_url}}/v1/unidades-organizacionais?skip=0&top=10&cnpj=0002&razaoSocial=fake
###

### UnidadeOrganizacional_Obter_500
GET {{base_url}}/v1/unidades-organizacionais
###


### UnidadeOrganizacional_ObterPorId_200
GET {{base_url}}/v1/unidades-organizacionais/
{{unidade_organizacional_fake_id}}
###

### UnidadeOrganizacional_ObterPorId_404
GET {{base_url}}/v1/unidades-organizacionais/{{general_fake_id_for_all_situations}}
###

### UnidadeOrganizacional_ObterPorId_500
GET {{base_url}}/v1/unidades-organizacionais/{{unidade_organizacional_fake_id}}
###


### UnidadeOrganizacional_Atualizar_200_Fake
PUT {{base_url}}/v1/unidades-organizacionais/{{unidade_organizacional_fake_id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "matrizId": null,
  "cnpj": "60163639000110",
  "razaoSocial": "Ricardo e Isis Marketing ME [Fake]",
  "nomeFantasia": null,
  "cep": null,
  "endereco": null,
  "numero": null,
  "bairro": null,
  "cidade": null,
  "uf": null,
  "pais": null,
  "email": null,
  "telefone": null
}
###

### UnidadeOrganizacional_Atualizar_400_CamposVazios
PUT {{base_url}}/v1/unidades-organizacionais/{{unidade_organizacional_fake_id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "matrizId": null,
  "cnpj": null,
  "razaoSocial": null,
  "nomeFantasia": null,
  "cep": null,
  "endereco": null,
  "numero": null,
  "bairro": null,
  "cidade": null,
  "uf": null,
  "pais": null,
  "email": null,
  "telefone": null
}
###

### UnidadeOrganizacional_Atualizar_400_CnpjInvalido
PUT {{base_url}}/v1/unidades-organizacionais/{{unidade_organizacional_fake_id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "matrizId": null,
  "cnpj": "1610404700013B",
  "razaoSocial": "Ricardo e Isis Marketing ME [Fake]",
  "nomeFantasia": null,
  "cep": null,
  "endereco": null,
  "numero": null,
  "bairro": null,
  "cidade": null,
  "uf": null,
  "pais": null,
  "email": null,
  "telefone": null
}
###

### UnidadeOrganizacional_Atualizar_400_RegistroDuplicado
PUT {{base_url}}/v1/unidades-organizacionais/{{unidade_organizacional_fake_id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "matrizId": null,
  "cnpj": "60935686000134",
  "razaoSocial": "Ricardo e Isis Marketing ME [Fake]",
  "nomeFantasia": null,
  "cep": null,
  "endereco": null,
  "numero": null,
  "bairro": null,
  "cidade": null,
  "uf": null,
  "pais": null,
  "email": null,
  "telefone": null
}
###

### UnidadeOrganizacional_Atualizar_404
PUT {{base_url}}/v1/unidades-organizacionais/{{general_fake_id_for_all_situations}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "matrizId": null,
  "cnpj": "45907344000117",
  "razaoSocial": "Ricardo e Isis Marketing ME [Fake]",
  "nomeFantasia": null,
  "cep": null,
  "endereco": null,
  "numero": null,
  "bairro": null,
  "cidade": null,
  "uf": null,
  "pais": null,
  "email": null,
  "telefone": null
}
###

### UnidadeOrganizacional_Atualizar_500
PUT {{base_url}}/v1/unidades-organizacionais/{{unidade_organizacional_fake_id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "matrizId": null,
  "cnpj": "45907344000117",
  "razaoSocial": "Ricardo e Isis Marketing ME [Fake]",
  "nomeFantasia": null,
  "cep": null,
  "endereco": null,
  "numero": null,
  "bairro": null,
  "cidade": null,
  "uf": "Minas Gerais",
  "pais": null,
  "email": null,
  "telefone": null
}
###


### UnidadeOrganizacional_Excluir_204
DELETE {{base_url}}/v1/unidades-organizacionais/{{unidade_organizacional_fake_id}}
Authorization: Bearer {{token}}
###

### UnidadeOrganizacional_Excluir_404
DELETE {{base_url}}/v1/unidades-organizacionais/{{general_fake_id_for_all_situations}}
Authorization: Bearer {{token}}
###

### UnidadeOrganizacional_Excluir_500
DELETE {{base_url}}/v1/unidades-organizacionais/{{general_fake_id_for_all_situations}}
Authorization: Bearer {{token}}
###


### UnidadeOrganizacional_Obter_200_Oficial
# @name UnidadeOrganizacionalOficialId
GET {{base_url}}/v1/unidades-organizacionais?skip=0&top=1&cnpj=60935686000134
###

### Espaco_Cadastrar_201_Oficial
POST {{base_url}}/v1/espacos
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}",
  "nome": "Sede",
  "descricao": "Rua Tamoios, 329, Centro, Moema - MG"
}
###

### Espaco_Cadastrar_201_Fake
POST {{base_url}}/v1/espacos
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}",
  "nome": "(Fake)",
  "descricao": "Fake description"
}
###

### Espaco_Cadastrar_400_CamposInvalidos
POST {{base_url}}/v1/espacos
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "unidadeOrganizacionalId": null,
  "nome": null,
  "descricao": null
}
###

### Espaco_Cadastrar_400_RegistroDuplicado
POST {{base_url}}/v1/espacos
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}",
  "nome": "(Fake)",
  "descricao": null
}
###

### Espaco_Cadastrar_500
POST {{base_url}}/v1/espacos
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}",
  "nome": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
  "descricao": null
}
###


### Espaco_Obter_200
GET {{base_url}}/v1/espacos
Authorization: Bearer {{token}}
###

### Espaco_Obter_200_ComPaginacao
GET {{base_url}}/v1/espacos?skip=1&top=1
Authorization: Bearer {{token}}
###

### Espaco_Obter_200_ComFiltro
# @name EspacoFakeId
GET {{base_url}}/v1/espacos?skip=0&top=10&nome=fake&unidadeOrganizacional={{unidade_organizacional_oficial_id}}
Authorization: Bearer {{token}}
###

### Espaco_Obter_200_Vazio
GET {{base_url}}/v1/espacos?skip=0&top=10&nome=xxx&unidadeOrganizacional={{unidade_organizacional_oficial_id}}
Authorization: Bearer {{token}}
###

### Espaco_Obter_500
GET {{base_url}}/v1/espacos
Authorization: Bearer {{token}}
###


### Espaco_ObterPorId_200
GET {{base_url}}/v1/espacos/{{espaco_fake_id}}
Authorization: Bearer {{token}}
###

### Espaco_ObterPorId_404
GET {{base_url}}/v1/espacos/{{general_fake_id_for_all_situations}}
Authorization: Bearer {{token}}
###

### Espaco_ObterPorId_500
GET {{base_url}}/v1/espacos/{{espaco_fake_id}}
Authorization: Bearer {{token}}
###


### Espaco_Atualizar_200_Fake
PUT {{base_url}}/v1/espacos/{{espaco_fake_id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}",
  "nome": "[Fake]",
  "descricao": "Fake sample"
}
###

### Espaco_Atualizar_400_CamposVazios
PUT {{base_url}}/v1/espacos/{{espaco_fake_id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "unidadeOrganizacionalId": null,
  "nome": null,
  "descricao": null
}
###

### Espaco_Atualizar_400_RegistroDuplicado
PUT {{base_url}}/v1/espacos/{{espaco_fake_id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}",
  "nome": "Sede",
  "descricao": "Fake sample"
}
###

### Espaco_Atualizar_404
PUT {{base_url}}/v1/espacos/{{general_fake_id_for_all_situations}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}",
  "nome": "[ Fake ]",
  "descricao": "Fake sample"
}
###

### Espaco_Atualizar_500
PUT {{base_url}}/v1/espacos/{{espaco_fake_id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}",
  "nome": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
  "descricao": null
}
###


### Espaco_Excluir_204
DELETE {{base_url}}/v1/espacos/{{espaco_fake_id}}
Authorization: Bearer {{token}}
###

### Espaco_Excluir_404
DELETE {{base_url}}/v1/espacos/{{general_fake_id_for_all_situations}}
Authorization: Bearer {{token}}
###

### Espaco_Excluir_500
DELETE {{base_url}}/v1/espacos/{{general_fake_id_for_all_situations}}
Authorization: Bearer {{token}}
###


# AUTH - LOGIN

### Auth_Login_200_Sucesso
# @name Login
POST {{base_url}}/v1/auth/login
Content-Type: application/json

{
  "username": "73999160352",
  "senha": "123456",
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}"
}
###

### Auth_Login_400_UsernameVazio
POST {{base_url}}/v1/auth/login
Content-Type: application/json

{
  "username": "",
  "senha": "123",
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}"
}
###

### Auth_Login_400_SenhaVazia
POST {{base_url}}/v1/auth/login
Content-Type: application/json

{
  "username": "37991974987",
  "senha": "",
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}"
}
###

### Auth_Login_400_UnidadeVazia
POST {{base_url}}/v1/auth/login
Content-Type: application/json

{
  "username": "37991974987",
  "senha": "123",
  "unidadeOrganizacionalId": null
}
###

### Auth_Login_401_UsuarioNaoEncontrado
POST {{base_url}}/v1/auth/login
Content-Type: application/json

{
  "username": "88888888888",
  "senha": "123",
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}"
}
###

### Auth_Login_401_SenhaIncorreta
POST {{base_url}}/v1/auth/login
Content-Type: application/json

{
  "username": "37991974987",
  "senha": "111",
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}"
}
###

### Auth_Login_401_UsuarioNaoValidado
POST {{base_url}}/v1/auth/login
Content-Type: application/json

{
  "username": "999999999999",
  "senha": "123",
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}"
}
###


# AUTH - FORGOT (ESQUECER SENHA)

### Auth_Forgot_200_Sucesso
POST {{base_url}}/v1/auth/forgot
Content-Type: application/json

{
  "username": "37991974987",
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}"
}
###

### Auth_Forgot_404_UsuarioNaoEncontrado
# Exception: "Usuário não encontrado."
POST {{base_url}}/v1/auth/forgot
Content-Type: application/json

{
  "username": "37991974987",
  "unidadeOrganizacionalId": "{{unidade_organizacional_oficial_id}}"
}
###


# AUTH - VERIFY (VERIFICAR CÓDIGO SMS)

### Auth_Verify_200_Sucesso
POST {{base_url}}/v1/auth/verify
Content-Type: application/json

{
  "codigoSms": "123456"
}
###

### Auth_Verify_400_CodigoVazio
# Exception: "Informe o código."
POST {{base_url}}/v1/auth/verify
Content-Type: application/json

{
  "codigoSms": ""
}
###

### Auth_Verify_404_CodigoNaoEncontrado
# Exception: "Código não encontrado."
POST {{base_url}}/v1/auth/verify
Content-Type: application/json

{
  "codigoSms": "999999"
}
###

### Auth_Verify_400_CodigoJaUtilizado
# Exception: "Este código já foi utilizado."
POST {{base_url}}/v1/auth/verify
Content-Type: application/json

{
  "codigoSms": "CODIGO_JA_USADO"
}
###

### Auth_Verify_400_TempoExpirado
# Exception: "O tempo de validação deste código expirou."
POST {{base_url}}/v1/auth/verify
Content-Type: application/json

{
  "codigoSms": "CODIGO_VELHO"
}
###

### Auth_Verify_400_NovaSolicitacaoFeita
# Exception: "Este código foi invalidado porque uma nova solicitação foi feita."
POST {{base_url}}/v1/auth/verify
Content-Type: application/json

{
  "codigoSms": "CODIGO_SUBSTITUIDO"
}
###


# AUTH - RESET (REDEFINIR SENHA)

### Auth_Reset_200_Sucesso
POST {{base_url}}/v1/auth/reset
Content-Type: application/json

{
  "codigoAcessoId": "COLE_O_CODIGO_ACESSO_ID_AQUI",
  "senha": "nova_senha_segura"
}
###

### Auth_Reset_400_CodigoAcessoVazio
# Exception: "Código de acesso não informado."
POST {{base_url}}/v1/auth/reset
Content-Type: application/json

{
  "codigoAcessoId": "",
  "senha": "nova_senha_segura"
}
###

### Auth_Reset_400_SenhaVazia
# Exception: "Informe a nova senha."
POST {{base_url}}/v1/auth/reset
Content-Type: application/json

{
  "codigoAcessoId": "COLE_O_CODIGO_ACESSO_ID_AQUI",
  "senha": ""
}
###

### Auth_Reset_404_CodigoAcessoNaoEncontrado
# Exception: "Código de acesso inválido ou não encontrado."
POST {{base_url}}/v1/auth/reset
Content-Type: application/json

{
  "codigoAcessoId": "id_inexistente_ou_invalido",
  "senha": "nova_senha_segura"
}
###

### Auth_Reset_400_NaoValidado
# Exception: "Este código não foi validado. Volte e informe os 6 dígitos primeiro."
POST {{base_url}}/v1/auth/reset
Content-Type: application/json

{
  "codigoAcessoId": "id_de_codigo_nao_validado",
  "senha": "nova_senha_segura"
}
###

### Auth_Reset_400_ResetJaEfetuado
# Exception: "Este código de acesso já foi utilizado."
POST {{base_url}}/v1/auth/reset
Content-Type: application/json

{
  "codigoAcessoId": "id_de_codigo_ja_resetado",
  "senha": "nova_senha_segura"
}
###

### Auth_Reset_400_TempoLimiteExpirado
# Exception: "O tempo limite para utilizar este código expirou. Solicite um novo código."
POST {{base_url}}/v1/auth/reset
Content-Type: application/json

{
  "codigoAcessoId": "id_de_codigo_expirado",
  "senha": "nova_senha_segura"
}
###

### Auth_Reset_400_SessaoExpirada
# Exception: "Esta sessão expirou porque um novo código foi solicitado recentemente."
POST {{base_url}}/v1/auth/reset
Content-Type: application/json

{
  "codigoAcessoId": "id_de_codigo_substituido",
  "senha": "nova_senha_segura"
}
###